management:
  endpoints:
    web:
      exposure:
        include: '*'
eureka:
  client:
    enabled: false
spring:
  cloud:
    gateway:
      enabled: false
      redis:
        enabled: false
      discovery:
        enabled: false
  mustache:
    check-template-location: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://auth.nelsonjohns.com/realms/turbolessons
