management:
  endpoints:
    web:
      exposure:
        include: '*'
logging:
  level:
    root: INFO
spring:
  cloud:
    gateway:
      enabled: false
      redis:
        enabled: false
    discovery:
      enabled: false
  mustache:
    check-template-location: false
  jackson:
    mapper:
      propagate-transient-marker: true
  security:
    oauth2:
      client:
        provider:
          okta:
            token-uri: https://auth.nelsonjohns.com/realms/turbolessons/protocol/openid-connect/token
        registration:
          okta:
            authorization-grant-type: client_credentials
            client-id: api-tests-m2m
            client-secret: '{cipher}AQDM7XiX9CPoePJqYlfR8X5dwjHZ44jms/wJa39/UABdbryEqDqKyXEL9n/5TaieMWu42uA+kQ/8Npbuz4Mls/Vo20rIif6aDUp4Tqppm5QeSsIKQ68FwCU0xLOsseHjVhIOY/Cimwe3axFOe1/4ztPzMuNFYS1fmlyDcVXZaSoPTHEL5ZZRmd3sACBI5VkR5iraFWy6/OkjCRMmfJ5yrLpxXjibP+uDE8m/gzBbZOSR3RAeq8CYVlQTB/hN/ks1iBmGuyCKE7f03SPG/L2kKe45QbIK2Pdl8d2QsbmWacNX5c84iUyS6iGiEZvK+NYHsKU0aUX3hyYrxySVUPpF5CQRgTzNPQSm2mAM+H6L9V0Yq6k73tMhxwdS8ZY7WvikXirL//h7+JgjR8IJy6/MeAy2OC3zTvphR56ABUZydDV5HQ=='
            scope: test_client
      resourceserver:
        jwt:
          issuer-uri: https://auth.nelsonjohns.com/realms/turbolessons
