spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: api-gateway
            client-secret: '{cipher}AQCy0w86DrKP0sv+cLZIPsbNWefiGIg9RwjVMP7aX0kZvAwdtM10nvIcDEjMY8Y9P5Z+EqBf1faSNyF4TSHDRsYGVnV7a2rsCU7f4bPB354UDuC4UbWDYeRY/8s7R/5gx7RYWU59ZYPNrO7362jKplYnIMBSaMGmsLZm0tabnvjC5ezmFXMJzyiedFimn3DVwcVEd19tTfUea7XOp6l889WCMNOZDh+UXBd6fmYwDOl0mqI9FZ13VQPJDB7zCER9QISprva3UDjw+qD6kre6099R9WNECMzXIepnyt6c2Cq5KU4E+whZwwgepjmmRCd54gp4LrdCZqwpqfnBrZtQD+rqtoGsTUmhgkb1B7BwamcrmAZUKIyKVQiF9EC0M2DxDY7LQvOwgvG3MPBPRu/W8SM5QlH3ihoMkdgOHAzqEanXGw=='
            authorization-grant-type: authorization_code
            scope: openid, profile, email
            redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"
        provider:
          keycloak:
            issuer-uri: https://auth.nelsonjohns.com/realms/turbolessons
      resourceserver:
        jwt:
          issuer-uri: https://auth.nelsonjohns.com/realms/turbolessons
  cloud:
    gateway:
      routes:
        - id: event-service
          uri: lb://event-service
          predicates:
            - Path=/api/lessons/**
          filters:
            - TokenRelay=
        - id: admin-service
          uri: lb://admin-service
          predicates:
            - Path=/api/users/**, /api/users
          filters:
            - TokenRelay=
        - id: message-service
          uri: lb://message-service
          predicates:
            - Path=/api/messages/**, /ws/messages/**
          filters:
            - TokenRelay=
        - id: email-service
          uri: lb://email-service
          predicates:
            - Path=/api/email/**
          filters:
            - TokenRelay=
        - id: video-service
          uri: lb://video-service
          predicates:
            - Path=/api/video/**, /api/video
          filters:
            - TokenRelay=
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/api/payments/**, /api/payments
          filters:
            - TokenRelay=
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI}
    healthcheck:
      enabled: true
cors:
  allowed-origins:
    - https://www.turbolessons.com
    - http://localhost:3000
logging:
  level:
    root: WARN
    org:
      springframework: INFO